version: '3.8'

services:
  # MySQL数据库
  mysql:
    image: mysql:8.0
    container_name: chewytta-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chewytta
      MYSQL_USER: chewytta
      MYSQL_PASSWORD: chewytta123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - chewytta-network
    restart: unless-stopped

  # Redis缓存
  redis:
    image: redis:latest
    container_name: chewytta-redis
    command: redis-server --requirepass redis123456
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - chewytta-network
    restart: unless-stopped

  # 后端服务
  backend:
    build:
      context: ./Chewytta
      dockerfile: Dockerfile
    container_name: chewytta-backend
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/chewytta?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
      - SPRING_DATASOURCE_USERNAME=chewytta
      - SPRING_DATASOURCE_PASSWORD=chewytta123
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PASSWORD=redis123456
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    networks:
      - chewytta-network
    restart: unless-stopped
    volumes:
      - ./ChewyApp:/app/ChewyApp
      - ./AdminContent:/app/AdminContent

  # 前端服务
  frontend:
    build:
      context: ./chewytta_fronted
      dockerfile: Dockerfile.simple
    container_name: chewytta-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - chewytta-network
    restart: unless-stopped

volumes:
  mysql_data:
  redis_data:


networks:
  chewytta-network:
    driver: bridge
